# Generated by Django 3.2.7 on 2021-09-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=300)),
                ('institution', models.CharField(max_length=300, null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
