# Generated by Django 3.2.7 on 2021-10-31 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_password_recovery_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='password_recovery_token',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
