# Generated by Django 3.2.7 on 2021-09-13 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usertask',
            table='UserTask',
        ),
    ]
