# Generated by Django 3.2.7 on 2021-09-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
                ('color', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'Subject',
            },
        ),
    ]
