# Generated by Django 3.2.7 on 2021-09-13 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20210913_1823'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usersubject',
            table='UserSubject',
        ),
    ]
