# Generated by Django 3.2.7 on 2021-10-23 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_alter_usersubject_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='priority',
        ),
    ]
